# Generated by Django 5.2.17 on 2026-09-17 12:52

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FRUITS", "Fruits"),
                            ("VEGETABLES", "Vegetables"),
                            ("DAIRY", "Dairy"),
                            ("MEAT", "Meat"),
                            ("SEAFOOD", "Seafood"),
                            ("GRAINS", "Grains"),
                            ("BAKERY", "Bakery"),
                            ("SNACKS", "Snacks"),
                            ("BEVERAGES", "Beverages"),
                            ("FROZEN", "Frozen"),
                            ("PACKAGED", "Packaged"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kg"),
                            ("g", "g"),
                            ("litres", "litres"),
                            ("ml", "ml"),
                            ("pieces", "pieces"),
                            ("packet", "packet"),
                            ("box", "box"),
                            ("can", "can"),
                            ("bottle", "bottle"),
                            ("dozen", "dozen"),
                        ],
                        default="pieces",
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(default=datetime.date.today)),
                ("expiry_date", models.DateField()),
                (
                    "storage_location",
                    models.CharField(
                        choices=[
                            ("REFRIGERATOR", "Refrigerator"),
                            ("FREEZER", "Freezer"),
                            ("PANTRY", "Pantry"),
                            ("KITCHEN", "Kitchen"),
                            ("OTHER", "Other"),
                        ],
                        default="PANTRY",
                        max_length=30,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="food_photos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("EXPIRING_SOON", "Expiring Soon"),
                            ("EXPIRED", "Expired"),
                            ("CONSUMED", "Consumed"),
                            ("SHARED", "Shared"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Item",
                "verbose_name_plural": "Food Items",
                "ordering": ["expiry_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="foods_foodi_user_id_11708b_idx"
                    ),
                    models.Index(
                        fields=["user", "expiry_date"],
                        name="foods_foodi_user_id_b28568_idx",
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="foods_foodi_user_id_1d4b4b_idx",
                    ),
                    models.Index(
                        fields=["user", "storage_location"],
                        name="foods_foodi_user_id_9d42f5_idx",
                    ),
                ],
            },
        ),
    ]
