# Generated by Django 5.2.17 on 2026-09-18 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.CreateModel(
            name="ConsumptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "consumed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_records",
                        to="foods.fooditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumption Record",
                "verbose_name_plural": "Consumption Records",
                "ordering": ["-consumed_at"],
            },
        ),
        migrations.CreateModel(
            name="WasteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("EXPIRED", "Expired"),
                            ("SPOILED", "Spoiled"),
                            ("BOUGHT_TOO_MUCH", "Bought Too Much"),
                            ("NOT_CONSUMED", "Not Consumed"),
                            ("OTHER", "Other"),
                        ],
                        default="EXPIRED",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("wasted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_records",
                        to="foods.fooditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste Record",
                "verbose_name_plural": "Waste Records",
                "ordering": ["-wasted_at"],
            },
        ),
    ]
