# Generated by Django 5.2.17 on 2026-09-21 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_alter_fooditem_quantity_consumptionrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooditem",
            options={
                "ordering": ["expiry_date"],
                "verbose_name": "Food Item",
                "verbose_name_plural": "Food Items",
            },
        ),
        migrations.RemoveIndex(
            model_name="fooditem",
            name="foods_foodi_user_id_11708b_idx",
        ),
        migrations.RemoveIndex(
            model_name="fooditem",
            name="foods_foodi_user_id_b28568_idx",
        ),
        migrations.RemoveIndex(
            model_name="fooditem",
            name="foods_foodi_user_id_1d4b4b_idx",
        ),
        migrations.RemoveIndex(
            model_name="fooditem",
            name="foods_foodi_user_id_9d42f5_idx",
        ),
        migrations.AddIndex(
            model_name="consumptionrecord",
            index=models.Index(fields=["user"], name="foods_consu_user_id_d5ef3f_idx"),
        ),
        migrations.AddIndex(
            model_name="consumptionrecord",
            index=models.Index(
                fields=["consumed_at"], name="foods_consu_consume_c335c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(fields=["user"], name="foods_foodi_user_id_e71dbc_idx"),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(fields=["status"], name="foods_foodi_status_57e61c_idx"),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                fields=["category"], name="foods_foodi_categor_bcae20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                fields=["expiry_date"], name="foods_foodi_expiry__424322_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                fields=["created_at"], name="foods_foodi_created_e96376_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wasterecord",
            index=models.Index(fields=["user"], name="foods_waste_user_id_21ad2e_idx"),
        ),
        migrations.AddIndex(
            model_name="wasterecord",
            index=models.Index(
                fields=["wasted_at"], name="foods_waste_wasted__d64fbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wasterecord",
            index=models.Index(fields=["reason"], name="foods_waste_reason_a4897b_idx"),
        ),
    ]
