# Generated by Django 5.2.17 on 2026-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={
                "ordering": ["name"],
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartments",
            },
        ),
        migrations.AddField(
            model_name="apartment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
