# Generated by Django 5.2.17 on 2026-09-16 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("RESIDENT", "Resident"), ("ADMIN", "Admin")],
                default="RESIDENT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("COMMUNITY", "Community"),
                            ("APARTMENT", "Apartment"),
                            ("PRIVATE", "Private"),
                        ],
                        default="COMMUNITY",
                        max_length=20,
                    ),
                ),
                (
                    "community_visibility",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("ALL", "All"),
                            ("PRIVATE", "Private"),
                        ],
                        default="APARTMENT",
                        max_length=20,
                    ),
                ),
                ("expiry_notifications", models.BooleanField(default=True)),
                ("share_notifications", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
    ]
