# Generated by Django 5.2.17 on 2026-09-19 11:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("foods", "0002_alter_fooditem_quantity_consumptionrecord_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "initial_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment Residents"),
                            ("NEIGHBOURS", "Neighbours / Community"),
                        ],
                        default="APARTMENT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("PARTIALLY_CLAIMED", "Partially Claimed"),
                            ("CLAIMED", "Claimed"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("pickup_note", models.TextField(blank=True, default="")),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="foods.fooditem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Share",
                "verbose_name_plural": "Food Shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="shares.foodshare",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Share",
                "verbose_name_plural": "Saved Shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="shares.foodshare",
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Request",
                "verbose_name_plural": "Share Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="foodshare",
            index=models.Index(
                fields=["owner", "status"], name="shares_food_owner_i_c1d858_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodshare",
            index=models.Index(
                fields=["visibility", "status"], name="shares_food_visibil_df39a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodshare",
            index=models.Index(
                fields=["food_item", "status"], name="shares_food_food_it_909509_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedshare",
            constraint=models.UniqueConstraint(
                fields=("user", "share"), name="unique_user_saved_share"
            ),
        ),
        migrations.AddIndex(
            model_name="sharerequest",
            index=models.Index(
                fields=["share", "status"], name="shares_shar_share_i_81e502_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharerequest",
            index=models.Index(
                fields=["requester", "status"], name="shares_shar_request_4d1c5d_idx"
            ),
        ),
    ]
