# Generated by Django 5.2.17 on 2026-09-20 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("FOOD_SHARE", "Food Share"),
                            ("USER", "User"),
                            ("FOOD_ITEM", "Food Item"),
                        ],
                        default="FOOD_SHARE",
                        max_length=30,
                    ),
                ),
                ("target_id", models.CharField(max_length=100)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("INAPPROPRIATE_CONTENT", "Inappropriate Content"),
                            ("MISLEADING_LISTING", "Misleading Listing"),
                            ("SPAM", "Spam / Advertising"),
                            ("HARASSMENT", "Harassment or Abuse"),
                            ("DUPLICATE", "Duplicate Content"),
                            ("OTHER", "Other Concern"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="reports_rep_status_c732ef_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_rep_created_a6aabf_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="reports_rep_target__6b1f9a_idx",
                    ),
                    models.Index(
                        fields=["reporter"], name="reports_rep_reporte_101677_idx"
                    ),
                ],
            },
        ),
    ]
