# Generated by Django 5.2.17 on 2026-09-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXPIRY_WARNING", "Expiry Warning"),
                    ("EXPIRY_URGENT", "Expiry Urgent"),
                    ("FOOD_EXPIRED", "Food Expired"),
                    ("SHARE_CREATED", "Share Created"),
                    ("SHARE_REQUEST_RECEIVED", "Share Request Received"),
                    ("SHARE_REQUEST_APPROVED", "Share Request Approved"),
                    ("SHARE_REQUEST_REJECTED", "Share Request Rejected"),
                    ("SHARE_REQUEST_CANCELLED", "Share Request Cancelled"),
                    ("SHARE_CLAIMED", "Share Claimed"),
                    ("SHARE_CANCELLED", "Share Cancelled"),
                    ("SYSTEM", "System Notification"),
                ],
                default="EXPIRY_WARNING",
                max_length=30,
            ),
        ),
    ]
